In [1]:
import numpy as np

In [6]:
a = np.array([[1,1,1,1,1],[2,2,2,2,2]])
a

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [8]:
mask = np.zeros_like(a)
mask[0,0] = 1
mask

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.where(mask, a*2, a)

array([[2, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [20]:
b = np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
b[0:a.shape[0], 0:a.shape[1]] = a
print(b)

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
a.shape[0]

2